---
Name: mysite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'default'
#Email:
#  admin_email: ''
MySQLDatabase:
  connection_charset: 'utf8'
GDBackend:
  default_quality: 85
i18n:
  current_locale: 'en_GB'
  default_locale: 'en_GB'
Image:
  extensions:
    - BBImageExtension
SiteConfig:
  extensions:
    - BBSiteConfigExtension
SiteTree:
  create_default_pages: No
  nested_urls: Yes
DateField:
  default_config:
    showcalendar: Yes
LeftAndMain:
  extra_requirements_javascript:
    - "mysite/javascript/admin-analytics.js": []
